### ISSUE TITLE
predicting multiple keyphrases

### ISSUE THREAD

**Issue by A-Jacobson** [memray/seq2seq-keyphrase-pytorch#1]
Hi Rui,

This isn't directly related to your pytorch implementation but I read your paper and am interested in reproducing. Though I am confused about how the predictions are made at test time.

In your paper you split the one to many relationship between documents and phrases into pairs:
```python
doc1: phrase1
doc1: phrase2
doc1: phrase3
```
and use this to train a seq2seq task where we predict a phrase given a document.

I understand how we could directly use this to predict a single keyphrase given a document, but how do we predict multiple phrases at test time? 

concretely, once the model is trained shouldn't it behave deterministically? so that  `model(doc1)` always predicts `phrase1`?

thanks,
Austin

**Comment by memray** [comment]
Hi Austin,

Good point! Actually I used beam search as a surrogate to generate multiple phrases, returning the top probable phrases conditioned on the input text. The 5th and 6th [slides](http://memray.me/uploads/acl17-deep-keyphrase-generation-slides.pdf) might be helpful to you. During the search, taking each word must result in a new search branch, therefore we end up with many different phrases.

Thanks,
Rui

**Comment by A-Jacobson** [comment]
That makes sense! So the other keyphases are just the 2nd - n most likely sequences as scored by beam search. 

Just out of curiousity, have you tried setting up the learning objective by concatenation first the keywords together and generating everything in one go?

Something like:
 ‘doc1 : <sos> phrase1 <sep> phrase2 <sep> phrase3 <eos>’

**Comment by memray** [comment]
We are thinking of new methods to improve the performance, and we are doing something similar as you suggested. One tricky problem is that if we construct the output as one sequence, the decoder might be sensitive to the order of phrases.

**Comment by A-Jacobson** [comment]
Perhaps that can be avoided that with some data augmentation. Perhaps randomly shuffling the phrase order at training time. Kind of like random flips in cv.

**Comment by memray** [comment]
Yes exactly, that's the basic idea we are doing. We are also trying out some new mechanisms, but not done yet.

**Comment by A-Jacobson** [comment]
Cool! I'm planning to try it as well. I'm lazy so I just wanted to make sure there wasn't some obvious domain related reason you didn't set things up like that in the first place. Best of luck with your experiments, thanks for the conversation.

**Comment by memray** [comment]
No problem. It was nice discussing with you :D
