### ISSUE TITLE
could I run it on cpu?

### ISSUE THREAD

**Issue by carly95** [memray/seq2seq-keyphrase-pytorch#12]
I want to run it on my mac pro.  I find the '-gpuid' parameter in config.py, but how to change it  for running on cpu?

**Comment by memray** [comment]
Certainly, you can. I am always debugging on CPU. The gpu setting does not matter on CPU cases.

**Comment by carly95** [comment]
hi~ I got a runtimeError message when i run it on cpu:
NFO:root:Parameters:
exp/kp20k.ml.copy.bi-directional.20180904-084732
INFO:root:vocab_size    :    50000
09/04/2018 08:47:32 [INFO] train: Parameters:
INFO:root:max_unk_words    :    1000
09/04/2018 08:47:32 [INFO] train: vocab_size    :    50000
INFO:root:words_min_frequency    :    0
09/04/2018 08:47:32 [INFO] train: max_unk_words    :    1000
INFO:root:max_src_seq_length    :    300
09/04/2018 08:47:32 [INFO] train: words_min_frequency    :    0
INFO:root:min_src_seq_length    :    20
09/04/2018 08:47:32 [INFO] train: max_src_seq_length    :    300
INFO:root:max_trg_seq_length    :    8
09/04/2018 08:47:32 [INFO] train: min_src_seq_length    :    20
INFO:root:min_trg_seq_length    :    None
09/04/2018 08:47:32 [INFO] train: max_trg_seq_length    :    8
INFO:root:src_seq_length_trunc    :    None
09/04/2018 08:47:32 [INFO] train: min_trg_seq_length    :    None
INFO:root:trg_seq_length_trunc    :    None
09/04/2018 08:47:32 [INFO] train: src_seq_length_trunc    :    None
INFO:root:shuffle    :    1
09/04/2018 08:47:32 [INFO] train: trg_seq_length_trunc    :    None
INFO:root:lower    :    True
09/04/2018 08:47:32 [INFO] train: shuffle    :    1
INFO:root:dynamic_dict    :    True
09/04/2018 08:47:32 [INFO] train: lower    :    True
INFO:root:word_vec_size    :    300
09/04/2018 08:47:32 [INFO] train: dynamic_dict    :    True
INFO:root:position_encoding    :    False
09/04/2018 08:47:32 [INFO] train: word_vec_size    :    300
INFO:root:share_decoder_embeddings    :    False
09/04/2018 08:47:32 [INFO] train: position_encoding    :    False
INFO:root:share_embeddings    :    False
09/04/2018 08:47:32 [INFO] train: share_decoder_embeddings    :    False
INFO:root:encoder_type    :    rnn
09/04/2018 08:47:32 [INFO] train: share_embeddings    :    False
INFO:root:decoder_type    :    rnn
09/04/2018 08:47:32 [INFO] train: encoder_type    :    rnn
INFO:root:enc_layers    :    1
09/04/2018 08:47:32 [INFO] train: decoder_type    :    rnn
INFO:root:dec_layers    :    1
09/04/2018 08:47:32 [INFO] train: enc_layers    :    1
INFO:root:rnn_size    :    512
09/04/2018 08:47:32 [INFO] train: dec_layers    :    1
INFO:root:rnn_type    :    LSTM
09/04/2018 08:47:32 [INFO] train: rnn_size    :    512
INFO:root:input_feeding    :    False
09/04/2018 08:47:32 [INFO] train: rnn_type    :    LSTM
INFO:root:bidirectional    :    True
INFO:root:attention_mode    :    general
INFO:root:copy_attention    :    True
INFO:root:copy_mode    :    general
INFO:root:copy_input_feeding    :    False
INFO:root:reuse_copy_attn    :    False
INFO:root:copy_gate    :    False
INFO:root:cascading_model    :    False
INFO:root:data    :    data/kp20k/kp20k
INFO:root:vocab    :    data/kp20k/kp20k.vocab.pt
09/04/2018 08:47:32 [INFO] train: input_feeding    :    False
09/04/2018 08:47:32 [INFO] train: bidirectional    :    True
09/04/2018 08:47:32 [INFO] train: attention_mode    :    general
09/04/2018 08:47:32 [INFO] train: copy_attention    :    True
09/04/2018 08:47:32 [INFO] train: copy_mode    :    general
09/04/2018 08:47:32 [INFO] train: copy_input_feeding    :    False
09/04/2018 08:47:32 [INFO] train: reuse_copy_attn    :    False
09/04/2018 08:47:32 [INFO] train: copy_gate    :    False
09/04/2018 08:47:32 [INFO] train: cascading_model    :    False
09/04/2018 08:47:32 [INFO] train: data    :    data/kp20k/kp20k
09/04/2018 08:47:32 [INFO] train: vocab    :    data/kp20k/kp20k.vocab.pt
09/04/2018 08:47:32 [INFO] train: save_model    :    model
09/04/2018 08:47:32 [INFO] train: train_from    :    
09/04/2018 08:47:32 [INFO] train: gpuid    :    [0]
09/04/2018 08:47:32 [INFO] train: seed    :    9527
09/04/2018 08:47:32 [INFO] train: epochs    :    100
09/04/2018 08:47:32 [INFO] train: start_epoch    :    1
09/04/2018 08:47:32 [INFO] train: param_init    :    0.1
09/04/2018 08:47:32 [INFO] train: pre_word_vecs_enc    :    None
09/04/2018 08:47:32 [INFO] train: pre_word_vecs_dec    :    None
09/04/2018 08:47:32 [INFO] train: fix_word_vecs_enc    :    False
09/04/2018 08:47:32 [INFO] train: fix_word_vecs_dec    :    False
09/04/2018 08:47:32 [INFO] train: batch_size    :    128
09/04/2018 08:47:32 [INFO] train: batch_workers    :    4
09/04/2018 08:47:32 [INFO] train: optim    :    adam
09/04/2018 08:47:32 [INFO] train: max_grad_norm    :    5
09/04/2018 08:47:32 [INFO] train: truncated_decoder    :    0
09/04/2018 08:47:32 [INFO] train: dropout    :    0.5
09/04/2018 08:47:32 [INFO] train: train_ml    :    True
09/04/2018 08:47:32 [INFO] train: train_rl    :    False
09/04/2018 08:47:32 [INFO] train: loss_scale    :    0.5
INFO:root:save_model    :    model
INFO:root:train_from    :    
INFO:root:gpuid    :    [0]
INFO:root:seed    :    9527
INFO:root:epochs    :    100
INFO:root:start_epoch    :    1
INFO:root:param_init    :    0.1
INFO:root:pre_word_vecs_enc    :    None
INFO:root:pre_word_vecs_dec    :    None
INFO:root:fix_word_vecs_enc    :    False
INFO:root:fix_word_vecs_dec    :    False
INFO:root:batch_size    :    128
INFO:root:batch_workers    :    4
INFO:root:optim    :    adam
INFO:root:max_grad_norm    :    5
INFO:root:truncated_decoder    :    0
INFO:root:dropout    :    0.5
INFO:root:train_ml    :    True
INFO:root:train_rl    :    False
INFO:root:loss_scale    :    0.5
INFO:root:rl_method    :    0
09/04/2018 08:47:32 [INFO] train: rl_method    :    0
09/04/2018 08:47:32 [INFO] train: rl_start_epoch    :    2
09/04/2018 08:47:32 [INFO] train: must_teacher_forcing    :    True
09/04/2018 08:47:32 [INFO] train: teacher_forcing_ratio    :    0
09/04/2018 08:47:32 [INFO] train: scheduled_sampling    :    False
09/04/2018 08:47:32 [INFO] train: scheduled_sampling_batches    :    10000
09/04/2018 08:47:32 [INFO] train: learning_rate    :    0.001
09/04/2018 08:47:32 [INFO] train: learning_rate_rl    :    0.0001
09/04/2018 08:47:32 [INFO] train: learning_rate_decay    :    0.5
09/04/2018 08:47:32 [INFO] train: start_decay_at    :    8
09/04/2018 08:47:32 [INFO] train: start_checkpoint_at    :    2
09/04/2018 08:47:32 [INFO] train: decay_method    :    
09/04/2018 08:47:32 [INFO] train: warmup_steps    :    4000
09/04/2018 08:47:32 [INFO] train: run_valid_every    :    2
09/04/2018 08:47:32 [INFO] train: early_stop_tolerance    :    10
09/04/2018 08:47:32 [INFO] train: timemark    :    20180904-084732
09/04/2018 08:47:32 [INFO] train: save_model_every    :    200
09/04/2018 08:47:32 [INFO] train: report_every    :    2
09/04/2018 08:47:32 [INFO] train: exp    :    kp20k.ml.copy.bi-directional
INFO:root:rl_start_epoch    :    2
INFO:root:must_teacher_forcing    :    True
INFO:root:teacher_forcing_ratio    :    0
INFO:root:scheduled_sampling    :    False
INFO:root:scheduled_sampling_batches    :    10000
INFO:root:learning_rate    :    0.001
INFO:root:learning_rate_rl    :    0.0001
INFO:root:learning_rate_decay    :    0.5
INFO:root:start_decay_at    :    8
INFO:root:start_checkpoint_at    :    2
INFO:root:decay_method    :    
INFO:root:warmup_steps    :    4000
INFO:root:run_valid_every    :    2
INFO:root:early_stop_tolerance    :    10
INFO:root:timemark    :    20180904-084732
INFO:root:save_model_every    :    200
INFO:root:report_every    :    2
INFO:root:exp    :    kp20k.ml.copy.bi-directional
INFO:root:exp_path    :    exp/kp20k.ml.copy.bi-directional.20180904-084732
09/04/2018 08:47:32 [INFO] train: exp_path    :    exp/kp20k.ml.copy.bi-directional.20180904-084732
09/04/2018 08:47:32 [INFO] train: pred_path    :    pred/kp20k.ml.copy.bi-directional.20180904-084732
09/04/2018 08:47:32 [INFO] train: model_path    :    model/kp20k.ml.copy.bi-directional.20180904-084732
09/04/2018 08:47:32 [INFO] train: beam_search_batch_example    :    8
09/04/2018 08:47:32 [INFO] train: beam_search_batch_size    :    32
09/04/2018 08:47:32 [INFO] train: beam_search_batch_workers    :    4
09/04/2018 08:47:32 [INFO] train: beam_size    :    32
09/04/2018 08:47:32 [INFO] train: max_sent_length    :    5
09/04/2018 08:47:32 [INFO] train: must_appear_in_src    :    True
09/04/2018 08:47:32 [INFO] train: num_oneword_seq    :    10000
09/04/2018 08:47:32 [INFO] train: report_score_names    :    ['f_score@5_exact', 'f_score@5_soft', 'f_score@10_exact', 'f_score@10_soft']
09/04/2018 08:47:32 [INFO] train: Loading vocab from disk: data/kp20k/kp20k.vocab.pt
INFO:root:pred_path    :    pred/kp20k.ml.copy.bi-directional.20180904-084732
INFO:root:model_path    :    model/kp20k.ml.copy.bi-directional.20180904-084732
INFO:root:beam_search_batch_example    :    8
INFO:root:beam_search_batch_size    :    32
INFO:root:beam_search_batch_workers    :    4
INFO:root:beam_size    :    32
INFO:root:max_sent_length    :    5
INFO:root:must_appear_in_src    :    True
INFO:root:num_oneword_seq    :    10000
INFO:root:report_score_names    :    ['f_score@5_exact', 'f_score@5_soft', 'f_score@10_exact', 'f_score@10_soft']
INFO:root:Loading vocab from disk: data/kp20k/kp20k.vocab.pt
09/04/2018 08:47:32 [INFO] train: Loading train and validate data from 'data/kp20k/kp20k'
09/04/2018 08:47:32 [INFO] train: ======================  Dataset  =========================
INFO:root:Loading train and validate data from 'data/kp20k/kp20k'
INFO:root:======================  Dataset  =========================
INFO:root:#(train data size: #(one2many pair)=18771, #(one2one pair)=98929, #(batch)=803, #(average examples/batch)=123.199
09/04/2018 08:47:33 [INFO] train: #(train data size: #(one2many pair)=18771, #(one2one pair)=98929, #(batch)=803, #(average examples/batch)=123.199
INFO:root:#(valid data size: #(one2many pair)=2000, #(one2one pair)=10507, #(batch)=372
INFO:root:#(test data size:  #(one2many pair)=2000, #(one2one pair)=10241, #(batch)=366
INFO:root:#(vocab)=51042
INFO:root:#(vocab used)=50000
09/04/2018 08:47:38 [INFO] train: #(valid data size: #(one2many pair)=2000, #(one2one pair)=10507, #(batch)=372
09/04/2018 08:47:38 [INFO] train: #(test data size:  #(one2many pair)=2000, #(one2one pair)=10241, #(batch)=366
09/04/2018 08:47:38 [INFO] train: #(vocab)=51042
09/04/2018 08:47:38 [INFO] train: #(vocab used)=50000
09/04/2018 08:47:38 [INFO] train: ======================  Model Parameters  =========================
09/04/2018 08:47:38 [INFO] train: Train a Seq2Seq model with Copy Mechanism
09/04/2018 08:47:38 [INFO] model: Training with All Teacher Forcing
INFO:root:======================  Model Parameters  =========================
INFO:root:Train a Seq2Seq model with Copy Mechanism
INFO:root:Training with All Teacher Forcing
/Users/mana/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/torch/nn/modules/rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
INFO:root:Applying Copy Mechanism, type=general
09/04/2018 08:47:39 [INFO] model: Applying Copy Mechanism, type=general
INFO:root:Model name: Seq2SeqLSTMAttention
INFO:root:number of parameters: 49323280
INFO:root:encoder: 4383744
INFO:root:decoder: 44939536
INFO:root:======================  Checking GPU Availability  =========================
INFO:root:Running on CPU!
INFO:root:======================  Start Training  =========================
09/04/2018 08:47:39 [INFO] utils: Model name: Seq2SeqLSTMAttention
09/04/2018 08:47:39 [INFO] utils: number of parameters: 49323280
09/04/2018 08:47:39 [INFO] utils: encoder: 4383744
09/04/2018 08:47:39 [INFO] utils: decoder: 44939536
09/04/2018 08:47:39 [INFO] train: ======================  Checking GPU Availability  =========================
09/04/2018 08:47:39 [INFO] train: Running on CPU!
09/04/2018 08:47:39 [INFO] train: ======================  Start Training  =========================
09/04/2018 08:47:39 [ERROR] train: message
Traceback (most recent call last):
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/train.py", line 795, in main
    train_model(model, optimizer_ml, optimizer_rl, criterion, train_data_loader, valid_data_loader, test_data_loader, opt)
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/train.py", line 467, in train_model
    for batch_i, batch in enumerate(train_data_loader):
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 223, in __next__
    return self._process_next_batch(batch)
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 243, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 77, in _pin_memory_loop
    batch = pin_memory_batch(batch)
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 145, in pin_memory_batch
    return [pin_memory_batch(sample) for sample in batch]
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 145, in <listcomp>
    return [pin_memory_batch(sample) for sample in batch]
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 145, in pin_memory_batch
    return [pin_memory_batch(sample) for sample in batch]
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 145, in <listcomp>
    return [pin_memory_batch(sample) for sample in batch]
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 139, in pin_memory_batch
    return batch.pin_memory()
RuntimeError: Pinned memory requires CUDA. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.

ERROR:root:message
Traceback (most recent call last):
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/train.py", line 795, in main
    train_model(model, optimizer_ml, optimizer_rl, criterion, train_data_loader, valid_data_loader, test_data_loader, opt)
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/train.py", line 467, in train_model
    for batch_i, batch in enumerate(train_data_loader):
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 223, in __next__
    return self._process_next_batch(batch)
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 243, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 77, in _pin_memory_loop
    batch = pin_memory_batch(batch)
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 145, in pin_memory_batch
    return [pin_memory_batch(sample) for sample in batch]
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 145, in <listcomp>
    return [pin_memory_batch(sample) for sample in batch]
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 145, in pin_memory_batch
    return [pin_memory_batch(sample) for sample in batch]
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 145, in <listcomp>
    return [pin_memory_batch(sample) for sample in batch]
  File "/Users/mana/PycharmProjects/seq2seq-keyphrase-pytorch-master/pykp/dataloader.py", line 139, in pin_memory_batch
    return batch.pin_memory()
RuntimeError: Pinned memory requires CUDA. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.


Process finished with exit code 0
----------------------------------------------------------
parameters like this:
-data
data/kp20k/kp20k
-vocab
data/kp20k/kp20k.vocab.pt
-exp
"kp20k"
-save_model_every
200
-run_valid_every
2
-report_every
2
-train_ml
-batch_size
128
-bidirectional
-input_feeding
-copy_attention
-copy_input_feeding
-must_teacher_forcing

**Comment by memray** [comment]
Hi @carly95,

Sorry for being late. I fixed the bug of pin_memory in the latest update. Please check it out and let me know if there's any problem.

Rui
