### ISSUE TITLE
A question about reproducing the results

### ISSUE THREAD

**Issue by xzwu20** [memray/seq2seq-keyphrase-pytorch#14]
Hi @memray, thanks for sharing the code.
How do I reproduce the results in the paper by training a new model?

**Comment by mkadaba** [comment]
Hi -- I have the same question.  I have downloaded the subset of 20k docs from the google drive link in the README, unzipped and placed in pykp/data/.   I have tried to run train.py from command line but get error: the following arguments are required: -data, -vocab  [This is even after I provide arguments in the command line]
What is the equivalent of keyphrase/keyphrase_copynet.py in this version?

**Comment by memray** [comment]
Hi,

I think the current implementation cannot reproduce the 100% same performance as in paper (Theano), because I only implement a simple CopyNet and it doesn't cover every detail. But it is workable and can generate reasonable outputs. You can refer to this [setting](https://github.com/memray/seq2seq-keyphrase-pytorch/blob/master/script/train-kp20k-bidirectional-copy-general.sh) I used to start running.

Thanks,
Rui

**Comment by xzwu20** [comment]
Thanks for your replies.
I have run the latest code according to your setting. Final Test-f_score@10_exact is around 0.1.
Note that I met some errors when attempting to run the code (e.g., the option -copy_model doesn't exist in the latest code). So I sincerely hope you check and update scripts.

**Comment by memray** [comment]
Sorry, I have refactored some configs and you should use the flag -copy_attention instead of -copy_model to enable copy mode. Try it out to see if it works. I think the current score should be around 0.25.

**Comment by xzwu20** [comment]
Thanks. I'll try it again.

**Comment by xzwu20** [comment]
Hi,

I have trained the model for 20000 batches (batch_size = 128). But reported Test-f_score@10_exact is 0.096 and reported Test-f_score@10_soft is 0.243. 
Here is the command I used

> CUDA_VISIBLE_DECIVE=0 PYTHONPATH=. python3 train.py -data data/kp20k/kp20k -vocab data/kp20k/kp20k.vocab.pt -exp_path "exp/attn_general.input_feeding.copy/%s.%s" -model_path "model/attn_general.input_feeding.copy/%s.%s" -pred_path "pred/attn_general.input_feeding.copy/%s.%s" -exp "kp20k" -bidirectional -copy_attention -run_valid_every 5000 -save_model_every 50000 -train_ml -input_feeding -batch_size 128 -beam_search_batch_size 16 -attention_mode general -gpuid 0

I set a larger beam_size (32 rather than 16). But I don't think it is so important to result in the gap between 0.096 and 0.25.

So what went wrong? :) Or I omitted some important options? :)

**Comment by memray** [comment]
It should not be this bad even beam size is small. You are running the master branch right?

**Comment by xzwu20** [comment]
Yes. The latest commit is on Sep 26.

**Comment by love2poppy** [comment]
Hi, @memray 
I want to know which F_1@K in your paper on the dataset KP20k did you use, exact version or soft?

**Comment by love2poppy** [comment]
> Sorry, I have refactored some configs and you should use the flag -copy_attention instead of -copy_model to enable copy mode. Try it out to see if it works. I think the current score should be around 0.25.

Did you use all ground-truth keyphrases in the predicting present keyphrases task, while in absent keyphrases task, only use absent keyphrases as ground-truth? So, the 0.25 is the F@10 score of the predicting present keyphrases task, right?

**Comment by love2poppy** [comment]
@memray 你好，我在你的theano版的项目里看到了如果需要复现present结果就如此`set config['predict_filter'] and config['target_filter'] to 'appear-only'`，是不是可以理解为论文中present的F@k值是只考虑了present keyphrase，只在文中出现过的短语，ground truth和predict都是如此。而absent则只考察了没有在文中出现过的短语。
还烦请解答
