### ISSUE TITLE
How to extract my own keyphrase?

### ISSUE THREAD

**Issue by boom85423** [memray/seq2seq-keyphrase-pytorch#19]
Hello:

I think your code is amazing but the README is too few to understand.
Excuse me, How to extract my own keyphrase?
* which one is the main entry file
* What data format should be input 

Thanks you!!!

Best regards.

**Comment by memray** [comment]
**train.py**: entry for preprocessing datasets in JSON format.
**train.py**: entry for training models.
**predict.py**: entry for generating phrases with well-trained models (checkpoints).

Please refer to these [scripts](https://github.com/memray/seq2seq-keyphrase-pytorch/tree/master/script) as examples, which may offer some clues about how to run the code.
