### ISSUE TITLE
I have a question for the file pykp/io.py

### ISSUE THREAD

**Issue by houwenxin** [memray/seq2seq-keyphrase-pytorch#20]
When reading your code, I found code as follows:
`if opt.src_seq_length_trunc and len(src) > opt.src_seq_length_trunc:
            src_tokens = src_tokens[:opt.src_seq_length_trunc]
`
I am puzzled about why it is len(src) here. I think we are calculating the number of words in the source sequence. Maybe it should be len(src_tokens) ?

**Comment by houwenxin** [comment]
The code is at around line 287 in io.py.

**Comment by memray** [comment]
Yes, you are right. The current code is truncating src by the string length. Fixed now.
