### ISSUE TITLE
The document

### ISSUE THREAD

**Issue by GabrielLin** [memray/seq2seq-keyphrase-pytorch#22]
Dear @memray , could you please write a document about installation and usage of this repo just like the original one. Thanks.

**Comment by memray** [comment]
Sorry about the incomplete instruction. I am working on other projects and will not be maintaining this repo for a while. 

Overall the repo is working. Please refer to these [scripts](https://github.com/memray/seq2seq-keyphrase-pytorch/tree/master/script), which may offer some clues about how to run the code.
