### ISSUE TITLE
data preprocess

### ISSUE THREAD

**Issue by waynedane** [memray/seq2seq-keyphrase-pytorch#24]
Hi Rui,  i dont't wanna replace digit terms with DIGIT . So i  comment line 301 in [https://github.com/memray/seq2seq-keyphrase-pytorch/blob/master/pykp/io.py](url) .However, the preprocessed data still repalces digit terms with DIGIT.

**Comment by memray** [comment]
I'm not sure what's happening. Line 301 should be the only place for replacing DIGIT. Can you check what the problem is?

**Comment by zhyq** [comment]
> Hi Rui, i dont't wanna replace digit terms with DIGIT . So i comment line 301 in [https://github.com/memray/seq2seq-keyphrase-pytorch/blob/master/pykp/io.py](url) .However, the preprocessed data still repalces digit terms with DIGIT.

After deleting  those *.tmp files, run preprocess.py

**Comment by memray** [comment]
@zhyq thank you for pointing it out :D
