### ISSUE TITLE
Testing the model

### ISSUE THREAD

**Issue by pidugusundeep** [memray/seq2seq-keyphrase-pytorch#25]
Hey @memray ,

I was able to train the model and I have a couple of questions for testing the same model,
1. I was running the 'predict-kp20k-bidirectional.sh' script for testing and had the JSON as the input file but I don't see the log printing the results for that JSON
2. Is the entry path for the code correct ? or is that loading from 'kp20k.valid.one2many.pt' is sp how do I generate the .pt file for a custom JSON?

I am stuck here and don't know what exactly I should be looking at for the data testing? and where exactly the results are dumped?
Please help me in this regard.

**Comment by memray** [comment]
You

**Comment by pidugusundeep** [comment]
Many of the parameters are commented and not sure what they exactly mean, it would be great if you could add a little more details for each and every configuration, i modified and i was running the script ```python -m predict -train_from Sundeep/seq2seq-keyphrase-pytorch/exp/rnn.kp20k.multi_test.general/kp20k.ml.copy.20190708-124223/model/kp20k.ml.copy.epoch=1.batch=1100.total_batch=1100.model -data data/kp20k/kp20k -vocab_path data/kp20k/kp20k.vocab.pt -exp_path "exp/kp20k" -exp "kp20k"  -bidirectional -batch_size 16 -beam_search_batch_size 1 -batch_workers 4 -must_appear_in_src -beam_size 16```
but i was always able to see that only 5 predictions are being generated is there a limitation for that ? is it getting from any configuration ? as i had around 10 json objects in ```kp20k_testing.json``` but its only generating 5 folders with the first five objects alone.

**Comment by SundeepPidugu** [comment]
@memray is this the line which i have to comment to run prediction against all the testing files ? https://github.com/memray/seq2seq-keyphrase-pytorch/blob/0ead6807194eed4e45937a14df8786c00f6a32dc/evaluate.py#L202-L204

**Comment by memray** [comment]
Feel free to remove that if statement, that's for local debugging. Sorry about it lol

**Comment by pidugusundeep** [comment]
@memray 

Hey instead of passing a document abstract can pass give it the entire document changing this **300** to a larger number? https://github.com/memray/seq2seq-keyphrase-pytorch/blob/0ead6807194eed4e45937a14df8786c00f6a32dc/config.py#L251
and is it mandatory to even change the **300** here as well for testing, I trained with **300** earlier  https://github.com/memray/seq2seq-keyphrasepytorch/blob/0ead6807194eed4e45937a14df8786c00f6a32dc/config.py#L146

Do I have to use the same .vocab for testing, which I was earlier used for training? I was having issues with the array list ``` index out of range``` so this is how I am using it : I was creating the onetomany.pt which was generated from the testing.json file using ```prediction.py``` and the generated vocab which I earlier used for training the mode for my testing purpose is that the correct procedure for my testing JSON file ??

Is there by any chance you have an updated ReadME with explaining all the configurations, please?

**Comment by memray** [comment]
Yes, you need to use the same vocab as used in training since the model greatly relies on it. I don't think the length matters much and you can adjust it freely. We won't update this repository for a while because of other ongoing projects. Sorry about it. But feel free to raise any questions.
