### ISSUE TITLE
UnboundLocalError when training the model

### ISSUE THREAD

**Issue by jennifer1995** [memray/seq2seq-keyphrase-pytorch#30]
when I use the command to train the model

`CUDA_VISIBLE_DEVICES=5,6 python train.py -data_path_prefix ../seq2seq-keyphrase-pytorch/data-ori/kp20k/kp20k -vocab_path ../dmcproject/seq2seq-keyphrase-pytorch/data-ori/kp20k/kp20k.vocab.pt`

it occurs the error below :

Traceback (most recent call last):
  File "train.py", line 890, in <module>
    main()
  File "train.py", line 883, in main
    train_model(model, optimizer_ml, optimizer_rl, criterion, train_data_loader, valid_data_loaders, test_data_loaders, opt)
  File "train.py", line 511, in train_model
    predict_save_path=opt.pred_path + '/epoch%d_batch%d_total_batch%d/' % (epoch, batch_i, total_batch))
  File "/home2/yy/dmcproject/seq2seq-keyphrase-pytorch/evaluate.py", line 166, in evaluate_multiple_datasets
    predict_save_path=os.path.join(predict_save_path, dataset_name))
  File "/home2/yy/dmcproject/seq2seq-keyphrase-pytorch/evaluate.py", line 258, in evaluate_beam_search
    match_list = get_match_result(true_seqs=filtered_trg_str_seqs, pred_seqs=processed_pred_str_seqs)
UnboundLocalError: local variable 'filtered_trg_str_seqs' referenced before assignment

related code is below (evaluate.py, line 258)

```
 # 1st filtering
pred_is_valid_flags, processed_pred_seqs, processed_pred_str_seqs, processed_pred_score = process_predseqs(pred_seq, oov, opt.id2word, opt)
# 2nd filtering: if filter out phrases that don't appear in text, and keep unique ones after stemming
if opt.must_appear_in_src:
        pred_is_present_flags, _ = if_present_duplicate_phrases(src_str, processed_pred_str_seqs)
        filtered_trg_str_seqs = np.asarray(trg_str_seqs)[trg_str_is_present_flags]
else:
        pred_is_present_flags = [True] * len(processed_pred_str_seqs)

valid_and_present = np.asarray(pred_is_valid_flags) * np.asarray(pred_is_present_flags)
match_list = get_match_result(true_seqs=filtered_trg_str_seqs, pred_seqs=processed_pred_str_seqs)
print_out += '[PREDICTION] #(valid)=%d, #(present)=%d, #(retained&present)=%d, #(all)=%d\n' % (sum(pred_is_valid_flags), sum(pred_is_present_flags), sum(valid_and_present), len(pred_seq))
print_out += ''
```

Thank you very much!

**Comment by memray** [comment]
It looks like an error with the evaluation during training. Try the following code:
```
if opt.must_appear_in_src:
        pred_is_present_flags, _ = if_present_duplicate_phrases(src_str, processed_pred_str_seqs)
        filtered_trg_str_seqs = np.asarray(trg_str_seqs)[trg_str_is_present_flags]
else:
        pred_is_present_flags = [True] * len(processed_pred_str_seqs)
        filtered_trg_str_seqs = np.asarray(trg_str_seqs) # add this line
```


This repo has been deprecated. Please move to https://github.com/memray/OpenNMT-kpg-release for the latest code.
