### ISSUE TITLE
Request ! Not a issue please provide step by step instruction to  train,test and predict for the KP20K data.

### ISSUE THREAD

**Issue by rajeshkumargp** [memray/seq2seq-keyphrase-pytorch#4]
Hi, Most of the predict script seems to have 
"model_path  ${directory_exp}/kp20k.bi-directional.no-loss-mask.20171117-214914/kp20k.epoch=1.batch=8000.total_batch=8000.model" 
But this file is not at all specified.  

 1)   Can you please provide step by step instruction to 
train,test and predict for the KP20K data. 
 2) what are the .pt files.. is those are pickeled binaries.. ? Please provide details.

**Comment by memray** [comment]
All these scripts are used for training on clusters on my end, may not be useful to you.
Data pre-processing is done by [preprocess.py](https://github.com/memray/seq2seq-keyphrase-pytorch/blob/master/preprocess.py)]. You'll see .pt files after running it. Then using `train.py` to start training.
